### ISSUE TITLE
BUG - cannot download Collab files on AWS

### ISSUE THREAD

**Issue by snamburi3** [overture-stack/score#227]
We are trying to download some data from collaboratory to AWS for analysis. The following command fails on AWS:
```
score-client --profile collab download --object-id 123456 --output-dir data
```

Here is the error message:
```
Starting...
                                                                                

Running...
                                                                                

Validating repository connection...
                                                                                
ERROR: Command error: java.io.IOException: Access refused by repository. Ensure client is running as part of repository cloud.
```

**Comment by rosibaj** [comment]
@snamburi3 We have just released a new version of the score client that should fix your issues. 

You can download the latest client here - https://docs.icgc.org/software/download/#latest-release-tarball 

Please let me know if you have any issues with this updated version.

**Comment by snamburi3** [comment]
@rosibaj,

I believe this bug is not resolved. I am getting the same error when I try to download collab files on AWS. Is there some parameter that I am missing?

This is what I am running on AWS
```   
export ACCESSTOKEN=$(cat ${token_file})
score-client --profile collab download --object-id 123456789 --output-dir data
```

**Comment by snamburi3** [comment]
Also, I am running the latest version of score-client:3.1.1

**Comment by wisekh6** [comment]
I also have the same issue. Any update?

**Comment by snamburi3** [comment]
Hello, any guidance on how to resolve this issue? could you please suggest any workaround?

**Comment by KevinFHartmann** [comment]
@snamburi3 Is this behaviour intermittent, or is it happening every time you try to download? If it's intermittent, how long does it seem to work on a given AWS instance before it begins to fail? 

It would be helpful to see if we can identify the conditions under which you're encountering this bug so that we can try to reproduce it.

**Comment by snamburi3** [comment]
@KevinFHartmann this is happening every time we try to download on AWS. The download never starts. I have done several tests so far and were never able to download Collab files on AWS. We are able to download the same collab files (with same pipeline) from Google Cloud and locally. 

I came across comment in score-client mentioning that collab restricts by ip? I am not sure if this is even relevant for this issue.

**Comment by KevinFHartmann** [comment]
@snamburi3 Okay... let's see...

1) What do you get when you run:`nslookup storage.cancercollaboratory.org` from the AWS instance?
2) What happens when you run: `ping -c 10 storage.cancercollaboratory.org`?

**Comment by snamburi3** [comment]
@KevinFHartmann Kevin, thank you. You pointed me in the right direction. I did some tests on the outgoing ports that are open (ours are restrictive). It works when I allow all outbound tcp ports on AWS.  What specific outbound ports need to be opened?

**Comment by KevinFHartmann** [comment]
@snamburi3 

You certainly need port 443 (https) for song and score. I think that's it; from what I remember, downloads from collab use port 443 as well. 

Try opening port 443, and let me know what happens, please!

**Comment by snamburi3** [comment]
@KevinFHartmann Thank you! Yes, that fixed the issue for me! Thanks much for debugging this with me. 

The following outgoing ports need to be open
HTTPS: 443 
Custom TCP: 9080 
Also, maybe the linux service ports (32768 - 61000)

Closing the issue.
